inherit_gem:
  rubocop-inst:
  - rubocop.yml

require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5

# ModBus's master/slave terminology isn't changing
Naming/InclusiveLanguage:
  Enabled: false

Style/BlockDelimiters:
  AllowedMethods: []
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
