#!/usr/bin/env ruby
# frozen_string_literal: true

require "aurora"
require "ccutrer-serialport"
require "uri"

uri = URI.parse(ARGV[0])

args = if uri.scheme == "telnet" || uri.scheme == "rfc2217"
         require "net/telnet/rfc2217"
         [Net::Telnet::RFC2217.new("Host" => uri.host,
                                   "Port" => uri.port || 23,
                                   "baud" => 19_200,
                                   "parity" => Net::Telnet::RFC2217::EVEN)]
       else
         [CCutrer::SerialPort.new(uri.path, baud: 19_200, parity: :even)]
       end

client = ModBus::RTUClient.new(*args)
client.logger = Logger.new($stdout, :debug)
slave = client.with_slave(1)

registers = slave.holding_registers[ARGV[1].to_i]

puts registers.inspect
