#!/usr/bin/env ruby
# frozen_string_literal: true

require "aurora"
require "ccutrer-serialport"
require "logger"
require "optparse"
require "yaml"

debug_modbus = monitor = mock = false

options = OptionParser.new do |opts|
  opts.banner = "Usage: web_aid_tool /path/to/serial/port [options]"

  opts.on("--debug-modbus", "Print actual protocol bytes") { debug_modbus = true }
  opts.on("--mock",
          "Instead of talking to an actual heat pump, mock it with registers from the given YAML file (instead of a serial port)") do # rubocop:disable Layout/LineLength
    mock = true
  end
  opts.on("--monitor", "Print interperted registers as they are requested, like aurora_monitor") { monitor = true }
  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end

options.parse!

unless ARGV.length == 1
  puts options
  exit 1
end

class MockSlave
  def initialize(registers)
    @registers = registers
  end

  def read_multiple_holding_registers(*queries)
    result = {}
    queries.each do |query|
      Array(query).each do |i|
        result[i] = @registers[i]
      end
    end
    result
  end

  def write_holding_register(addr, value)
    @registers[addr] = value
  end
end

if mock
  slave = MockSlave.new(YAML.load_file(ARGV[0]))
else
  uri = URI.parse(ARGV[0])

  args = case uri.scheme
         when "tcp"
           require "socket"
           [TCPSocket.new(uri.host, uri.port)]
         when "telnet", "rfc2217"
           require "net/telnet/rfc2217"
           [Net::Telnet::RFC2217.new(uri.host,
                                     port: uri.port || 23,
                                     baud: 19_200,
                                     parity: :even)]
         else
           [CCutrer::SerialPort.new(uri.path, baud: 19_200, parity: :even)]
         end

  client = ModBus::RTUClient.new(*args)
  client.logger = Logger.new($stdout)
  client.logger.level = debug_modbus ? :debug : :warn

  slave = client.with_slave(1)
end

def parse_query_string(query_string)
  query_string.split("&").map { |p| p.split("=") }.to_h
end

# _don't_ do URI escaping
def encode_result(params)
  params.map { |p| p.join("=") }.join("&")
end

require "sinatra"

set :public_folder, "html"

get "/" do
  send_file "html/index.htm"
end

units = 0

get "/getunits.cgi" do
  encode_result(units: units)
end

get "/setunits.cgi" do
  units = params["units"].to_i
  encode_result(error: 0)
end

get "/config.cgi" do
  encode_result(
    "AWL Version" => Aurora::VERSION,
    "Local Web Version" => 1.08,
    "SSID" => nil,
    "Units" => units,
    "AWL ID" => ARGV[0],
    "AWL ID CRC" => nil
  )
end

get "/request.cgi" do
  params = parse_query_string(request.query_string)
  result = params.slice("cmd", "id", "set", "addr")
  result["err"] = nil

  # these are just aliases to get a certain set of registers
  case params["cmd"]
  when "abcinfo"
    params["regs"] = "2;8;88,4"
  when "devices"
    params["regs"] = "800;803;806,3;812;815;818;824"
  end

  case params["cmd"]
  when "getregs", "abcinfo", "devices"
    queries = params["regs"].split(";").map do |range|
      start, length = range.split(",").map(&:to_i)
      next start if length.nil?

      start...(start + length)
    end
    registers = slave.read_multiple_holding_registers(*queries)
    puts Aurora.print_registers(registers) if monitor
    result["values"] = registers.values.join(",")
  when "putregs"
    writes = params["regs"].split(";").map do |write|
      write.split(",").map(&:to_i)
    end.compact.to_h
    if monitor
      puts "WRITING"
      puts Aurora.print_registers(writes)
      puts "==="
    end

    writes.each do |(addr, value)|
      slave.write_holding_register(addr, value)
    end
  else
    return ""
  end

  encode_result(result)
end
